version: '3.8'

services:
  # 后端 FastAPI 服务
  backend:
    # 使用当前目录的 Dockerfile 进行构建
    build: .
    # 挂载整个项目根目录到容器的 /app 目录
    # 这样本地代码的修改会实时同步到容器中，方便开发
    volumes:
      - .:/app
      # 挂载宿主机的 Docker socket，允许容器内的应用与宿主机 Docker 守护进程通信
      - /var/run/docker.sock:/var/run/docker.sock
    # 映射端口，将主机的 8000 端口映射到容器的 8000 端口
    ports:
      - "8000:8000"
    # 从 .env 文件加载环境变量
    env_file:
      - .env
    # 设置服务依赖，确保 db 和 redis 服务先于 backend 启动
    depends_on:
      db
      redis

  # PostgreSQL 数据库服务
  db:
    # 使用 alpine 版本的 PostgreSQL 镜像，体积更小
    image: postgres:13-alpine
    # 挂载命名卷以持久化数据库数据
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # 从 .env 文件加载数据库相关的环境变量
    env_file:
      - .env
    # 将容器的 5432 端口映射到主机的 5432 端口，方便外部工具连接调试
    ports:
      - "5432:5432"

  # Redis 缓存服务
  redis:
    # 使用 alpine 版本的 Redis 镜像
    image: redis:6-alpine

# 定义命名卷，用于持久化 PostgreSQL 数据
volumes:
  postgres_data: 